In [1]:
import numpy as np

In [2]:
myarray = np.array([[3, 6, 32, 7]], np.int64)

In [3]:
myarray[0, 1]

6

In [4]:
myarray.shape

(1, 4)

In [5]:
myarray.dtype

dtype('int64')

In [6]:
myarray[0,1]

6

In [7]:
myarray[0,1]=45

In [8]:
myarray

array([[ 3, 45, 32,  7]], dtype=int64)

***Array Creation: Conversion from other Python structures (e.g., lists, tuples)***

In [9]:
listarray = np.array([[1,2,3], [5,8,5], [0,3,1]])
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [10]:
listarray.dtype

dtype('int32')

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.size

9

In [13]:
np.array({32, 33, 45})

array({32, 33, 45}, dtype=object)

In [14]:
zero = np.zeros((2,4))

In [15]:
zero

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
rng = np.arange(16)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
lspace = np.linspace(1,50,10)

In [19]:
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [20]:
emp = np.empty((4,6))

In [21]:
emp

array([[ 8.34423493e-308,  6.89795984e-307,  1.22387805e-307,
         1.42418172e-306,  8.06609645e-308, -2.90264426e-310],
       [ 1.22387550e-307, -4.58529492e-311,  6.01347002e-154,
         5.92878775e-322,  9.23607407e-300, -2.97585311e-310],
       [ 9.23607407e-300,  9.23607407e-300,  5.59776377e-321,
         2.02369289e-320,  4.24399158e-313, -2.98794846e-310],
       [ 1.03878562e-013,  1.03878562e-013,  6.95095622e-307,
         1.22387805e-307,  2.22522596e-306, -3.05521572e-310]])

In [22]:
emp_like = np.empty_like(lspace)

In [23]:
emp_like

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [24]:
ide = np.identity(10)

In [25]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
ide.shape

(10, 10)

In [27]:
arr = np.arange(33)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [29]:
arr.reshape(3,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]])

In [30]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [31]:
arr.shape

(33,)

In [32]:
x = [[1,2,3], [4,5,6], [7,1,0]]
ar = np.array(x)

In [33]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [34]:
ar.sum(axis=0)

array([12,  8,  9])

In [35]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [36]:
ar.flat

In [37]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [38]:
ar.ndim

2

In [39]:
ar.size

9

In [40]:
ar.nbytes

36

In [41]:
ond = np.array([1,3,4,634,2])

In [42]:
ond.argmax()

3

In [43]:
ond.argmin()

0

In [44]:
ond.argsort()

array([0, 4, 1, 2, 3], dtype=int64)

In [45]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [46]:
ar.argmin()

8

In [47]:
 ar.argmax()

6

In [48]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [49]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [50]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [51]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [52]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [53]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [54]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [55]:
ar2 = np.array([[1, 2, 1],
                [4, 0, 6],
                [8, 1, 0]])

In [56]:
ar + ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [57]:
ar * ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [58]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [59]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [60]:
ar.max()

7

In [65]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [68]:
np.where(ar>3)

(array([1, 1, 1, 2], dtype=int64), array([0, 1, 2, 0], dtype=int64))

In [69]:
np.count_nonzero(ar)

8

In [70]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [71]:
import sys

In [72]:
lst = [0,4,55,2]

In [73]:
np_ar = np.array(lst)

In [74]:
sys.getsizeof(1)*len(lst)

112

In [76]:
np_ar.itemsize*np_ar.size

16

In [77]:
np_ar.tolist()

[0, 4, 55, 2]